' This file is used by Code Analysis to maintain SuppressMessage
' attributes that are applied to this project.
' Project-level suppressions either have no target or are given
' a specific target and scoped to a namespace, type, member, etc.

Imports System.Diagnostics.CodeAnalysis

<Assembly: SuppressMessage("CodeQuality", "IDE0052:Remove unread private members", Justification:="<Pending>", Scope:="member", Target:="~F:BSMyLoadersLog.LoadersClass.BSAppConfig._DefaultDBName")>
<Assembly: SuppressMessage("CodeQuality", "IDE0052:Remove unread private members", Justification:="<Pending>", Scope:="member", Target:="~F:BSMyLoadersLog.LoadersClass.BSAppConfig._DefaultUserConfig")>
<Assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification:="<Pending>", Scope:="member", Target:="~F:BSMyLoadersLog.MDIParentMain.ISPROD")>
<Assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification:="<Pending>", Scope:="member", Target:="~F:BSMyLoadersLog.MDIParentMain.m_ChildFormNumber")>
<Assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification:="<Pending>", Scope:="member", Target:="~F:BSMyLoadersLog.MDIParentMain.m_ChildFormNumber")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.frmAddQtyPowder.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.frmAddQtyPowder.btnUpdate_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.frmAddQtyPowder.btnViewCalc_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.frmAddQtyPowder.frmAddQtyPowder_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.frmConfig_Add_Wizard_SG_2.btnNext_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.frmConfig_Add_Wizard_SG_2.chkPersonal_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.frmConfig_Add_Wizard_SG_2.cmdWAD_SelectedIndexChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.frmConfig_Add_Wizard_SG_2.frmConfig_Add_Wizard_SG_2_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.frmOptions.btnApply_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.frmOptions.btnExit_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.frmOptions.btnSave_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.frmOptions.chkSec_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.frmOptions.frmOptions_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.GlobalVars.CostOf1RndOfAmmo(System.Double,System.Double,System.Double,System.Double,System.Double)~System.Double")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.GlobalVars.CostOf1RndOfAmmoSG(System.Double,System.Double,System.Double,System.Double,System.Double,System.Double)~System.Double")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.GlobalVars.FluffContent(System.String,System.Double)~System.Double")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.GlobalVars.FluffContent(System.String,System.String)~System.String")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.GlobalVars.IsRequired(System.Double,System.Double,System.String,System.String)~System.Boolean")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.GlobalVars.IsRequired(System.Int64,System.Int64,System.String,System.String)~System.Boolean")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.GlobalVars.IsRequired(System.String,System.String,System.String)~System.Boolean")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.GlobalVars.UnFluffContent(System.String)~System.String")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.AutoFillCollections.MainCollection(System.String,System.String)~System.Windows.Forms.AutoCompleteStringCollection")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.AutoFillCollections.MainCollectionDistinct(System.String,System.String)~System.Windows.Forms.AutoCompleteStringCollection")>
<Assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.AutoFillCollections.ShotGun.MainCollection(System.String,System.String)~System.Windows.Forms.AutoCompleteStringCollection")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.AutoFillCollections.ShotGun.MainCollection(System.String,System.String)~System.Windows.Forms.AutoCompleteStringCollection")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.AutoFillCollections.ShotGun.MainCollectionDistinct(System.String,System.String)~System.Windows.Forms.AutoCompleteStringCollection")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.BSAppConfig.GetAppSetting(System.String)~System.String")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.BSDatabase.ConnExec(System.String)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.BSDatabase.GetData(System.String)~System.Data.DataTable")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.BSDatabase.sConnect~System.String")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.BSDatabase.sConnect~System.String")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.BSFileSystem.FileHasExtension(System.String)~System.Boolean")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.BSFileSystem.GetExtOfFile(System.String)~System.String")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.BSFileSystem.GetNameOfFile(System.String)~System.String")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.BSFileSystem.GetNameOfFileWOExt(System.String)~System.String")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.BSFileSystem.GetPathOfFile(System.String)~System.String")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.BSMGC.AddFirearmToMGC(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Int64@)")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.BSMGC.AmmoIsAlreadyListed(System.String,System.String,System.String,System.String,System.String,System.Int64@,System.Int64@)~System.Object")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.BSMGC.ConnExec(System.String)")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.BSMGC.CountFirearms~System.Int32")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.BSMGC.GetMGCEXEPath~System.String")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.BSMGC.GetMGCPath~System.String")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.BSMGC.GetName(System.String,System.String)~System.String")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.BSMGC.sConnect~System.String")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.BSMGC.sConnect~System.String")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.BSRegistry.GetLastWorkingDir~System.String")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.BSRegistry.GetRegSubKeyValue(System.String,System.String,System.String)~System.String")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.BSRegistry.GetViewSettings(System.String,System.String)~System.String")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.BSRegistry.RegSubKeyExists(System.String)~System.Boolean")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.BSRegistry.SetSettingDetails")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.GlobalFunctions.FormatForXML(System.String)~System.String")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.GlobalFunctions.FormatFromXML(System.String)~System.String")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.GlobalFunctions.GetAmmoTypeID(System.Object)~System.Int64")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.GlobalFunctions.GetAmmoTypeIDSG(System.Object)~System.Int64")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.GlobalFunctions.GetCaliberID(System.String,System.Boolean)~System.Int64")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.GlobalFunctions.GetTitle(System.Int64)~System.String")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.GlobalFunctions.IsShotGunCOnfig(System.Int64)~System.Boolean")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.Inventory_Export_Import.XML_Generate_Bushings_Powder_Import(System.String)")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.Inventory_Export_Import.XML_Generate_Bushings_Shot_Import(System.String)")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.Inventory_Export_Import.XML_Generate_Powder_Import(System.String)")>
<Assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.InventoryMath.ARUSG_UpdateInventoryQty(System.Int64,System.Int64,System.Int64,System.Int64,System.Int64,System.Int64,System.Int64,System.Double,System.Int64,System.Double,System.Int64,System.Int64,System.Boolean,System.Double,System.Double,System.Double)")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.InventoryMath.ConvertToDollars(System.Double)~System.Double")>
<Assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.InventoryMath.GetPowderDetails(System.Int64,System.String@,System.String@,System.Double,System.Double@,System.Double@,System.String@,System.Double@)")>
<Assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.LoadersClass.InventoryMath.LoadSG_ShotType_Details(System.Int64,System.String@,System.String@,System.Boolean@,System.String@,System.String@,System.String@,System.String@,System.Double@,System.Double@,System.Double@,System.Double@,System.Double@)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.MDIParentMain.btnAddCal2List_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.MDIParentMain.btnAddConfig_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.MDIParentMain.btnDelete_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.MDIParentMain.btnImportConfig_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.MDIParentMain.cmbConfigSort_SelectedIndexChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.MDIParentMain.CopyToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.MDIParentMain.DeleteToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.MDIParentMain.InitRegValues")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.MDIParentMain.lstCal_DoubleClick(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.MDIParentMain.lstCal_DoubleClick(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.MDIParentMain.lstCal_SelectedIndexChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.MDIParentMain.lstConfigSheets_DoubleClick(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.MDIParentMain.lstConfigSheets_SelectedIndexChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.MDIParentMain.MDIParent2_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.MDIParentMain.PowderToolStripMenuItem1_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.MDIParentMain.PowderToolStripMenuItem2_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.MDIParentMain.RiflePistolToolStripMenuItem1_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.MDIParentMain.ShellToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.MDIParentMain.ShotgunToolStripMenuItem1_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.MDIParentMain.ShotToolStripMenuItem2_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.MDIParentMain.tsslErrorsFound_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.MDIParentMain.tsslMGCEnabled_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.MDIParentMain.UseConfigurationToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.MDIParentMain.ViewConfigs")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyLoadersLog.MDIParentMain.WADToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="type", Target:="~T:BSMyLoadersLog.frmAddQtyPowder")>
